### ISSUE TITLE
Any chance to support PHP 5.6 ?

### ISSUE THREAD

**Issue by sarfraznawaz2005** [nunomaduro/laravel-zero#23]
Any chance to support PHP 5.6 as it is still widespread ?

Thanks

**Comment by GrahamCampbell** [comment]
For what it's worth. 👎

Mainly because Laravel 5.5 no longer supports PHP 5.6. :)

**Comment by nunomaduro** [comment]
Sorry @sarfraznawaz2005, but I agree with @GrahamCampbell.
