### ISSUE TITLE
The build feature is broken

### ISSUE THREAD

**Issue by nunomaduro** [nunomaduro/laravel-zero#3]
**Version:** 1.1.4
**PHP Version:** 7.1.2

**Description:**

After adding the feature "Adds compatibility with Laravel Services Providers" the build feature is broken. The main cause is the new following line on the Application.php:

```
        $this->container->instance('config', new Repository(
            require BASE_PATH . '/' . 'config/config.php'
        ));
```

Since now there is a require on the code, the following error appears on the usage of the Phar:

_PHP Warning:  require(phar:///Users/nunomaduro/Projects/laravel-zero/builds/test2/config/config.php): failed to open stream: phar error: "config/config.php"_

**Steps To Reproduce:**

1. Create a new Laravel Zero Project:

composer create-project --prefer-dist nunomaduro/laravel-zero application

2. Create a build of your project:

php application build

3. Execute your build:

php builds/application

**Comment by ilesinge** [comment]
Try to add 'config/' in Build::$structure ? This should do the trick.
